[package]
name = "fman"
version = "0.1.1"
description = "A simple file manager TUI"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ddanielsantos/fman"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
color-eyre = "0.6.3"
ratatui = "0.28.1"
