name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Generate build matrix
        uses: reitermarkus/rust-build-matrix@main
        id: generate-matrix  
  build:
    runs-on: ${{ matrix.os }}
    needs: generate-matrix
    strategy:
      matrix:
        include: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - run: |
          cargo build --target "${target}"
        env:
          target: ${{ matrix.target }}
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test
