name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install targets
      run: |
        rustup target add x86_64-apple-darwin
        rustup target add x86_64-pc-windows-gnu
    - name: Build for Linux
      run: cargo build --verbose
    - name: Build for macOS
      run: cargo build --target x86_64-apple-darwin --verbose
    - name: Build for Windows
      run: cargo build --target x86_64-pc-windows-gnu --verbose

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose